### ISSUE TITLE
[Feature request] Add 'Deselect All' button to the Hierarchy

### ISSUE THREAD

**Issue by HeCorr** [Vadim07/AssetStudio#1]
_(somewhat copied from https://github.com/Perfare/AssetStudio/issues/961)_

Hello!

I would like to request a feature that would allow me to de-select all checkboxes in the hierarchy because due to my current workflow I use "Go to scene hierarchy" from the Asset list all the time and when I need to export the next asset, the previous one is already scrolled away from the hierarchy view, forcing me to find it again just to de-select it.

Another option would be a setting that automatically de-selects all previously selected assets after exporting.

Thanks!

**Comment by aelurum** [comment]
Hi
You can try it now by downloading one of the versions from [appveyor](https://ci.appveyor.com/project/aelurum/assetstudio-mod/build/artifacts).
For example: [AssetStudioModGUI-net6-win64](https://ci.appveyor.com/api/buildjobs/6sj7fk59xqek605y/artifacts/AssetStudioGUI/bin/Release/net6.0-windows/win-x64/AssetStudioModGUI-net6-win64.v0.16.48.1.zip)
I added some options to a right-click menu, but keep in mind that depending on the number of nodes in the "Scene Hierarchy" tab, it may be slow.
As for "automatically de-selects", well I'll think about that a bit later.

**Comment by HeCorr** [comment]
thank you very much!

**Comment by HeCorr** [comment]
it doesn't seem to be launching when I click it.

**Comment by aelurum** [comment]
What exactly didn't launch?

**Comment by HeCorr** [comment]
AssetStudioGUI.exe, downloaded from the exact archive you suggested.

Em dom., 12 de mar. de 2023 23:42, VaDiM ***@***.***>
escreveu:

**Comment by aelurum** [comment]
I see
You likely need to update your [.NET 6 Desktop Runtime](https://dotnet.microsoft.com/download/dotnet/6.0) to run this version
And you can also try the [net472 version](https://ci.appveyor.com/api/buildjobs/6sj7fk59xqek605y/artifacts/AssetStudioGUI%2Fbin%2FRelease%2FAssetStudioModGUI-net472.v0.16.48.1.zip)

**Comment by HeCorr** [comment]
thanks! that worked, but I'm still having the errors I was having with the original version, which is why I tried using this fork to begin with.

I'll open a separate issue to report them.

**Comment by HeCorr** [comment]
Hello! So, indeed the de-selection performance is very slow with a large list so I was wondering if instead of looping through all the items it wouldn't be possible to just loop through the selected ones instead?

Surely the selection state is stored somewhere, which is how it knows which items to export, right? Or does the exporting code also loop through all the items in the list and exports the selected ones..?

**Comment by aelurum** [comment]
> Or does the exporting code also loop through all the items in the list and exports the selected ones..?
 
Almost)
And they are recursive functions, so they are a bit slow.
But yeah, it's worth to try to speed up it then.

Here, try this: [AssetStudioModGUI-net472](https://ci.appveyor.com/api/buildjobs/l8upx181848dsauw/artifacts/AssetStudioGUI%2Fbin%2FRelease%2FAssetStudioModGUI-net472.v0.16.48.1.zip) or [all artifacts](https://ci.appveyor.com/project/aelurum/assetstudio-mod/build/artifacts).

**Comment by HeCorr** [comment]
There you go, it's basically instantaneous now. Thank you very much!

I think you can close it now  :)

https://user-images.githubusercontent.com/75134774/234663476-9d4ed7ad-a46f-48e4-b21e-16328baf51ec.mp4
