### ISSUE TITLE
Error on Unity 2021.3 LZ4 compression

### ISSUE THREAD

**Issue by MetasharpDev** [Vadim07/AssetStudio#14]
For one piece bounty rush :
Files from this folder give errors:
com.bandainamcoent.opbrww\files\AssetBundle\assets
here's one file for you to debug:
https://gofile.io/d/yWM2ss

![image](https://github.com/aelurum/AssetStudio/assets/70144948/977e8568-8300-484b-b6ef-c6dc57ef56cc)

**Comment by aelurum** [comment]
Hi
It's not a problem of AssetStudio
Devs just use some kind of protection for some game assets
Can't help with that

**Comment by MetasharpDev** [comment]
When I try to build your source code to debug it, it's missing fbxsdk.h in AssetStudioFBXNative project.
Could you help?

**Comment by aelurum** [comment]
### [Build](https://github.com/aelurum/AssetStudio#build)
> AssetStudioFBXNative uses [FBX SDK 2020.2.1](https://www.autodesk.com/developer-network/platform-technologies/fbx-sdk-2020-2-1), before building, you need to install the FBX SDK (and change the project file, if you installed it to a non-default directory, change additional include directory and additional library directory to point to the FBX SDK directory)

**Comment by MetasharpDev** [comment]
Hi,
when loading One Piece Bounty Rush folder (where i got these errors), in fact I narrowed a few things after building it myself.
- It works with framework 4.7.2
- It freezes with framework 6 and 7 (something to fix there)
- you forgot to include the runtime folder in the released files

Here is a test folder to load that reproduces the issue:
https://gofile.io/d/xdjJyb
