### ISSUE TITLE
Unhandled exception has occured in your application. 

### ISSUE THREAD

**Issue by ShahirZaman** [Vadim07/AssetStudio#15]
this popped up
![image](https://github.com/aelurum/AssetStudio/assets/42411567/d4448bef-8526-4f08-b7da-257d2fa98bef)
this had popped up while i was trying to extract stuff from phas for animating, importing the phas folder causes this.
I did attempt to continue but nothing happened

this is the whole error
See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.IO.IOException: Stream was too long.
   at System.IO.MemoryStream.Write(Byte[] buffer, Int32 offset, Int32 count)
   at System.IO.Stream.InternalCopyTo(Stream destination, Int32 bufferSize)
   at AssetStudio.ImportHelper.DecompressGZip(FileReader reader) in L:\GIT\AssetStudioMod\AssetStudio\ImportHelper.cs:line 61
   at AssetStudio.AssetsManager.LoadFile(FileReader reader) in L:\GIT\AssetStudioMod\AssetStudio\AssetsManager.cs:line 148
   at AssetStudio.AssetsManager.Load(String[] files) in L:\GIT\AssetStudioMod\AssetStudio\AssetsManager.cs:line 116
   at AssetStudio.AssetsManager.LoadFilesAndFolders(String& parentPath, List`1 pathList) in L:\GIT\AssetStudioMod\AssetStudio\AssetsManager.cs:line 101
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at AssetStudioGUI.AssetStudioGUIForm.<loadFolder_Click>d__58.MoveNext() in L:\GIT\AssetStudioMod\AssetStudioGUI\AssetStudioGUIForm.cs:line 176
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()

************** Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9181.0 built by: NET481REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework64/v4.0.30319/mscorlib.dll
----------------------------------------
AssetStudioModGUI
    Assembly Version: 0.17.3.0
    Win32 Version: 0.17.3.0
    CodeBase: file:///I:/AssetStudioModGUI_net472_win32_64/AssetStudioModGUI.exe
----------------------------------------
System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9181.0 built by: NET481REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9172.0 built by: NET481REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Drawing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9037.0 built by: NET481REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
AssetStudioUtility
    Assembly Version: 0.17.3.0
    Win32 Version: 0.17.3.0
    CodeBase: file:///I:/AssetStudioModGUI_net472_win32_64/AssetStudioUtility.DLL
----------------------------------------
OpenTK
    Assembly Version: 3.3.3.0
    Win32 Version: 3.3.3
    CodeBase: file:///I:/AssetStudioModGUI_net472_win32_64/OpenTK.DLL
----------------------------------------
Microsoft.WindowsAPICodePack.Shell
    Assembly Version: 1.1.6.0
    Win32 Version: 1.1.6.0
    CodeBase: file:///I:/AssetStudioModGUI_net472_win32_64/Microsoft.WindowsAPICodePack.Shell.DLL
----------------------------------------
AssetStudio
    Assembly Version: 0.17.3.0
    Win32 Version: 0.17.3.0
    CodeBase: file:///I:/AssetStudioModGUI_net472_win32_64/AssetStudio.DLL
----------------------------------------
System.Core
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9181.0 built by: NET481REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
Mono.Cecil
    Assembly Version: 0.11.3.0
    Win32 Version: 0.11.3.0
    CodeBase: file:///I:/AssetStudioModGUI_net472_win32_64/Mono.Cecil.DLL
----------------------------------------
Microsoft.WindowsAPICodePack
    Assembly Version: 1.1.6.0
    Win32 Version: 1.1.6.0
    CodeBase: file:///I:/AssetStudioModGUI_net472_win32_64/Microsoft.WindowsAPICodePack.DLL
----------------------------------------
System.Configuration
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9037.0 built by: NET481REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System.Xml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9037.0 built by: NET481REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
OpenTK.GLControl
    Assembly Version: 3.3.3.0
    Win32 Version: 3.3.3
    CodeBase: file:///I:/AssetStudioModGUI_net472_win32_64/OpenTK.GLControl.DLL
----------------------------------------
AssetStudio.PInvoke
    Assembly Version: 0.17.3.0
    Win32 Version: 0.17.3.0
    CodeBase: file:///I:/AssetStudioModGUI_net472_win32_64/AssetStudio.PInvoke.DLL
----------------------------------------
System.Memory
    Assembly Version: 4.0.1.1
    Win32 Version: 4.6.28619.01
    CodeBase: file:///I:/AssetStudioModGUI_net472_win32_64/System.Memory.DLL
----------------------------------------
System.Runtime.CompilerServices.Unsafe
    Assembly Version: 5.0.0.0
    Win32 Version: 5.0.20.51904
    CodeBase: file:///I:/AssetStudioModGUI_net472_win32_64/System.Runtime.CompilerServices.Unsafe.DLL
----------------------------------------

************** JIT Debugging **************
To enable just-in-time (JIT) debugging, the .config file for this
application or computer (machine.config) must have the
jitDebugging value set in the system.windows.forms section.
The application must also be compiled with debugging
enabled.

For example:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

When JIT debugging is enabled, any unhandled exception
will be sent to the JIT debugger registered on the computer
rather than be handled by this dialog box.

**Comment by aelurum** [comment]
Hi
Try using the latest build on [AppVeyor](https://ci.appveyor.com/project/aelurum/assetstudiomod/branch/AssetStudioMod/artifacts)
The latest build should already avoid such issues
