### ISSUE TITLE
.Exe file available?

### ISSUE THREAD

**Issue by JackHarris1973** [Vadim07/AssetStudio#19]
Hi!  I really want to use this version of AssetStudio, but I have no idea how to compile this.  I've been working on this for an entire day, and it's just over my head.  Is there a .exe available for the GUI version of this for people like me who are completely ignorant of C++ or C# programming?

**Comment by JackHarris1973** [comment]
Never mind.  I found it, and TIL that I didn't understand how GitHub does things.

**Comment by aelurum** [comment]
It's ok
also, the new version should be released around this week, I think
