### ISSUE TITLE
Errors when loading Rust bundles

### ISSUE THREAD

**Issue by HeCorr** [Vadim07/AssetStudio#2]
Hello! I'm trying to load the bundles from the game Rust but am having errors since they updated it to Unity 2021.3.

I have 32GBs of RAM and used to be able to load all the bundles, but now that these errors started showing up, it consumes the entirety of my memory until my system crashes, while the progress bar is still barely at 5%.

It all seems to be related to [ReadInt32()](https://github.com/aelurum/AssetStudio/blob/01957a9443cad63e5c4298a3d7ad8158221dfc49/AssetStudio/EndianBinaryReader.cs#L65).. My wild guess is that Unity 2021.3 updated some of the data types to Int64 which started causing problems everywhere an Int32 value is expected.

Here are a few of the errors I was able to screenshot before it crashed:

<details>
  <summary>Screenshots</summary>

  ![2023-03-13 19-41-10](https://user-images.githubusercontent.com/75134774/224852115-20fc1484-d052-4de3-8c48-de50d196e42c.png)

![2023-03-13 19-41-17](https://user-images.githubusercontent.com/75134774/224852116-f6a4baa7-979c-412b-8522-c26adddabca2.png)

![2023-03-13 19-49-52](https://user-images.githubusercontent.com/75134774/224852119-0df8d0d9-f674-4252-8a42-270dbbd632bb.png)

![2023-03-13 19-51-34](https://user-images.githubusercontent.com/75134774/224852121-24fcb734-0a14-4fc2-9cfc-648364818f5c.png)

![2023-03-13 19-53-03](https://user-images.githubusercontent.com/75134774/224852123-0cc9ed7b-a216-4b69-a782-616706333550.png)

![2023-03-13 19-53-50](https://user-images.githubusercontent.com/75134774/224852125-894fae73-63c2-4b3c-b6a9-66e8ee71466f.png)

</details>

**Comment by HeCorr** [comment]
@aelurum are you able to look into this please? I'm not sure how I would setup the project on my machine.

**Comment by aelurum** [comment]
Yeah, I know about that.
AssetStudio has problems with Shader support for unity ver > 2020.
But I can't do much with that.
In fact, I can't continue Perfare's work and keep AssetStudio up to date or fix internal bugs.
This fork is mainly focused on UI modifications and functionality enhancements.

The only thing I can do is disable shader support for unity > 2020.
*(Which was already in my plans, actually).*
You can try it here: [AssetStudioMod net472 version](https://ci.appveyor.com/api/buildjobs/8pnyqga7quq6sfk2/artifacts/AssetStudioGUI%2Fbin%2FRelease%2FAssetStudioModGUI-net472.v0.16.48.1.zip).
Or if you want some other version: [artifacts](https://ci.appveyor.com/project/aelurum/assetstudio-mod/build/artifacts).

So, if you need shaders or support for the latest versions of Unity, you should use some other software, for example [AssetRipper](https://github.com/AssetRipper/AssetRipper).

**Comment by HeCorr** [comment]
I don't really know what Shaders are in this context, but I don't think I
need them.

All I need to export are meshes and textures, though the way I do it, AS
automatically exports related textures when I export a mesh so maybe that
has something to do with the shader, but yeah I don't think I need the
shaders themselves.

I'll give that a test right now, thank you very much!

Em seg., 20 de mar. de 2023 às 14:48, VaDiM ***@***.***>
escreveu:

**Comment by vertexgamer** [comment]
@aelurum thanks, worked like a charm.

**Comment by HeCorr** [comment]
Sorry, I forgot to get back to you. It's indeed working perfectly now,
thank you very much!

You can go ahead and close this. (I would but can't atm)

Em sex., 24 de mar. de 2023 16:15, vertexgamer ***@***.***>
escreveu:
