### ISSUE TITLE
SkinnedMeshRenderer won't open

### ISSUE THREAD

**Issue by JackHarris1973** [Vadim07/AssetStudio#20]
Hi, I'm trying to extract assets from a folder with about 33,800 .unity3d files.  I'm getting this message many times:

Unable to load object
Assets CAB-fa3d70dec379a6a5a618fa2d0d410bed
Path
C:\Users\jackj\OneDrive\Desktop\DHSG\Output\aRCNAME_03750b32.unity3d
Type SkinnedMeshRenderer
PathID 6841637308075437081
System.IO.EndOfStreamException: Unable to read beyond the end of the stream.
   at System.IO.BinaryReader.InternalRead(Int32 numBytes)
   at AssetStudio.EndianBinaryReader.ReadInt64() in
L:\GIT\AssetStudioMod\AssetStudio\EndianBinaryReader.cs:line 52
   at AssetStudio.SkinnedMeshRenderer...ctor(ObjectReader reader) in
L:\GIT\AssetStudioMod\AssetStudio\Classes\SkinnedMeshRenderer.cs:line 14
   at AssetStudio.AssetsManager.ReadAssets() in
L:\GIT\AssetStudioMod\AssetStudio\AssetsManager.cs:line 588

It seems like the same error message for all the files, and all the files are of type SkinnedMeshRenderer.

**Comment by JackHarris1973** [comment]
I would also add that this seems connected to a larger issue.  When I load all these files in the Perfare version of AssetStudio and turn error messaging off, I'm able to export Animator + Animation Clips, and the armature and animation files export correctly, but without the mesh.  I am far from an expert on any of this, but it seems likely that these two problems are related.

**Comment by aelurum** [comment]
Hi
You need to attach some assets as an example or at least write the game name

**Comment by JackHarris1973** [comment]
Sorry!  New to this.  The game is Dragonheir: Silent Gods.  I've attached a .zip with three of the files that are throwing errors.

[SkinnedMeshRenderer_Errors.zip](https://github.com/aelurum/AssetStudio/files/13655173/SkinnedMeshRenderer_Errors.zip)

**Comment by aelurum** [comment]
Yeah, I see
Devs modified the standard SkinnedMeshRenderer class, by adding some additional fields to it
And they also slightly modified the AnimationClip class

You can try this Studio:
[AssetStudioModGUI_DSG_net472.zip](https://github.com/aelurum/AssetStudio/files/13678046/AssetStudioModGUI_DSG_net472.zip)
[AssetStudioModGUI_DSG_net6_win64.zip](https://github.com/aelurum/AssetStudio/files/13678053/AssetStudioModGUI_DSG_net6_win64.zip)
It should be possible to load these customized assets with it
But don't try to use it for any other game, since the changes I made are not universal

**Comment by JackHarris1973** [comment]
Thank you so much.  That worked perfectly.  It was very generous of you to make a version of the app specifically for this one game.

**Comment by JackHarris1973** [comment]
Hi, I wanted to re-open this issue.  The Dragonheir-specific version of AssetStudioGUIMod is working quite well, but it seems that upon model export, the mesh's vertex groups are getting messed up.  The models look right in their default poses, but if one tries to pose them or add an animation to them, the mesh distorts badly.  Any way we can take another look at that version?

**Comment by aelurum** [comment]
Sad, but once again, I can't help with 3d stuff
Especially when the devs did something to their 3d models
Also, if you export a model with animationClip, then at least the exported animation works without problems
