### ISSUE TITLE
[Error] Export Sprite:summon_eleElemental_9 error

### ISSUE THREAD

**Issue by apple050620312** [Vadim07/AssetStudio#22]
[Error] Export Sprite:summon_eleElemental_9 error
[Error]
[Error] System.ArgumentOutOfRangeException: Parameter "width" (System.Int32) must be greater than 0, was 0
[Error] 參數名稱: width
[Error]    於 SixLabors.ThrowHelper.ThrowArgumentOutOfRangeException(String name, String message)
[Error]    於 SixLabors.ThrowHelper.ThrowArgumentOutOfRangeExceptionForMustBeGreaterThan[T](T value, T minimum, String name)
[Error]    於 SixLabors.ImageSharp.ImageFrame`1..ctor(Configuration configuration, Int32 width, Int32 height, ImageFrameMetadata metadata)
[Error]    於 SixLabors.ImageSharp.Processing.Processors.CloningImageProcessor`1.CreateTarget()
[Error]    於 SixLabors.ImageSharp.Processing.Processors.CloningImageProcessor`1.SixLabors.ImageSharp.Processing.Processors.ICloningImageProcessor<TPixel>.CloneAndExecute()
[Error]    於 SixLabors.ImageSharp.Processing.DefaultImageProcessorContext`1.ApplyProcessor(IImageProcessor processor, Rectangle rectangle)
[Error]    於 SixLabors.ImageSharp.Processing.DefaultImageProcessorContext`1.ApplyProcessor(IImageProcessor processor)
[Error]    於 SixLabors.ImageSharp.Processing.CropExtensions.Crop(IImageProcessingContext source, Rectangle cropRectangle)
[Error]    於 AssetStudio.SpriteHelper.<>c__DisplayClass2_0.<CutImage>b__0(IImageProcessingContext x) 於 L:\GIT\AssetStudioMod\AssetStudioUtility\SpriteHelper.cs: 行 108
[Error]    於 SixLabors.ImageSharp.Processing.ProcessingExtensions.Clone[TPixel](Image`1 source, Configuration configuration, Action`1 operation)
[Error]    於 AssetStudio.SpriteHelper.CutImage(Sprite m_Sprite, Texture2D m_Texture2D, Rectf textureRect, Vector2 textureRectOffset, Single downscaleMultiplier, SpriteSettings settingsRaw) 於 L:\GIT\AssetStudioMod\AssetStudioUtility\SpriteHelper.cs: 行 108
[Error]    於 AssetStudio.SpriteHelper.GetImage(Sprite m_Sprite, SpriteMaskMode spriteMaskMode) 於 L:\GIT\AssetStudioMod\AssetStudioUtility\SpriteHelper.cs: 行 30
[Error]    於 AssetStudioGUI.Exporter.ExportSprite(AssetItem item, String exportPath) 於 L:\GIT\AssetStudioMod\AssetStudioGUI\Exporter.cs: 行 246
[Error]    於 AssetStudioGUI.Studio.<>c__DisplayClass14_0.<ExportAssets>b__0(Object state) 於 L:\GIT\AssetStudioMod\AssetStudioGUI\Studio.cs: 行 477

**Comment by aelurum** [comment]
Hi
You need to attach this asset as an example or at least write the game name

**Comment by apple050620312** [comment]
Oh sorry the game is Soul Knight Prequel

**Comment by aelurum** [comment]
There's nothing I can do with that.
The sprites just don't have the necessary data to render images.
They look like placeholders, maybe there's some post-processing inside the game.
