### ISSUE TITLE
Go to scene hierarchy in CLI?

### ISSUE THREAD

**Issue by portablevampire** [Vadim07/AssetStudio#23]
Is it possible to view scene hierarchy of an asset in the CLI version, or export assets in folders that show scene hierarchy?
In the GUI version I use the go to scene hierarchy function a lot but it doesnt seem like there's an equivalent function in CLI, which means I have no way of finding some very necessary information about certain Monobehavior assets. Could this be added if it doesn't exist?

Before you tell me to just use the GUI version: i don't always have access to a windows machine so sometimes cli is all i can use.

**Comment by aelurum** [comment]
Hi
It sounds pretty troublesome, actually
But it's possible to add a flag to export the scene hierarchy as a json file
Would that be fine?

**Comment by aelurum** [comment]
> export assets in folders that show scene hierarchy

the problem here is that not every asset is associated with the scene hierarchy
so most of them just won't be sorted and will be placed in the same folder

**Comment by portablevampire** [comment]
a json file might work. really all i need to be able to do is see where in the scene hierarchy specific assets are (even if that means they arent in one)

as an example of a use case: there's a game i'm exploring assets for that uses the Fungus library for unity visual novels, and the different background scenes are stored in "View" monobehaviors. the monobehaviors themselves don't tell me much about the scene besides the aspect ratio, but the views are all sorted in the scene hierarchy under the name of the image asset that's used for the background, so right clicking and checking the scene hierarchy takes me directly to the name of the background asset. i can edit this post with a screenshot example of what i mean later once i'm able to use a windows machine, but basically i just need a way to see whether a monobehavior of a specific path ID is sorted into a scene hierarchy and if so, which specific branch it's under. if a json file can accomplish that, then it should work fine.

**Comment by portablevampire** [comment]
here's a quick recording demonstrating my use case. here i'm following unity/fungus VN dialogue trees for the chapter "Scene_465" by following path IDs. as you can see, the only way for me to get useful information about the views is to see the scene hierarchy that it's in. https://vimeo.com/897805439?share=copy

if there's a way for me to find the same information using CLI, that would be really useful.

**Comment by aelurum** [comment]
Well, in fact, since each asset already stores a link to its treeNode(if exists), it will be easier to just add the treeNode path to an exported xml asset list 🤔 

> export assets in folders that show scene hierarchy

I added this as one of the grouping options.
Assets which are not listed in the scene hierarchy will be exported to the "_sceneRoot" folder with grouping by type. I guess this is ok?

You can try it here: [artifacts](https://ci.appveyor.com/project/aelurum/assetstudiomod/build/artifacts)
- grouping by node path: `-g sceneHierarchy`
- export asset list: `--export-asset-list xml`
- export assets with PathID in names: `-f assetName_pathID`
