### ISSUE TITLE
Animation Export Order?

### ISSUE THREAD

**Issue by JackHarris1973** [Vadim07/AssetStudio#24]
Hi, when I'm using the Export-->Animator + selected AnimationClips, is there a way to change the order in which it exports the clips?  I have exported a model with two animation clips, and they're appearing in the order 2-then-1, when I need them in the order 1-then-2.  Fixing this afterwards in Noesis has proved to be impossible, and fixing it in Blender is terribly complicated.

This is for the game Transformers: Earth Wars.

I'm selecting the Animator file "main" (the lod0 version) and the AnimationClips:
transform_to_alt_hero
transform_to_main_hero

I want them to export in that order, but AssetStudio is reversing the order.  I've tried changing the order in which I select the AnimationClips, but it doesn't affect the export.

[grapple.zip](https://github.com/aelurum/AssetStudio/files/13796970/grapple.zip)

**Comment by aelurum** [comment]
You can try it, by downloading the latest version here: [artifacts](https://ci.appveyor.com/project/aelurum/assetstudiomod/builds/48853443/artifacts)

**Comment by JackHarris1973** [comment]
That worked perfectly.  I can't thank you enough; I spent five hours on this yesterday with no success.  You just saved me a massive amount of effort.
