### ISSUE TITLE
Hair textures distorted or masked on extraction

### ISSUE THREAD

**Issue by JackHarris1973** [Vadim07/AssetStudio#27]
When extracting models from Star Trek: Fleet Command, the models with hair are coming out with distorted hair textures.  I think there is some kind of translation that's happening in-game in order to make the models look correct in the game's gallery, but when extracted, the hair portions of the models' textures appear as brightly-colored blobs.  In the attached file, as an example, the character should have dark brown or black hair; instead, the color is a mixture of blues and greens.  I was hoping there was something that could be done in AssetStudio to compensate for this.

[STFC_Bashir.zip](https://github.com/aelurum/AssetStudio/files/14117661/STFC_Bashir.zip)

**Comment by aelurum** [comment]
Hi
Interesting, but AssetStudio can't do anything with this.
They just change the hair color in-game.
See no problems with the textures.
