### ISSUE TITLE
OutOfMemoryException error when reading an AssetBundle asset from Unity v5.4.0

### ISSUE THREAD

**Issue by aelurum** [Vadim07/AssetStudio#31]
> There's definitely a memory leak happening. Trying to open this https://mega.nz/file/9kQjlLyZ#-UYE2fcGA1po-b12h6d7AtnbkoEo0YmW2wdfiESjR0A causes memory usage to spike. It opens fine in Perfare's AssetStudio with the memory usage one would expect from a file this small.

> Haven't tested in the other net builds, but I'm using the net8 GUI version.

_Originally posted by @HallowSL in https://github.com/aelurum/AssetStudio/issues/30#issuecomment-2002291400_

**Comment by HallowSL** [comment]
I also found it happening with some unity version 2019.4.26f1 files. https://mega.nz/file/9w5HBbSA#CSEDTQqW1aiBfe80Nh0prfG29SiHQGtYag43w7CEHxs
