### ISSUE TITLE
Feature request: Import options

### ISSUE THREAD

**Issue by AzureBerylBlue** [Vadim07/AssetStudio#32]
Would it be possible to add Import options to Asset Studio so I could choose to exclude certain types of assets from being loaded. That way, I could for example, load a folder and skip loading the AudioClip assets if I want the models.

I was trying to load a folder full of assets with what look like randomly generated file names that were all unorganized and in one big folder, but loading too many assets at once eats up too much RAM, so a feature like this would be a big help.

**Comment by aelurum** [comment]
Filtering asset types before import is a good idea.
You may notice some implementation of this in the CLI version, where you can specify the asset types to load.
However, the implementation there is not very effective.
But for now I don't plan to work on it.

But don't be sad, there's also [AssetStudio](https://github.com/RazTools/Studio) by Razmoth, who actually implemented this in a pretty efficient way.
There you can create an asset map and a cab map, which allows you to filter assets before import.
And it's also possible to allow loading of only selected asset types in the settings.
You can read the tutorial here: https://gist.github.com/Modder4869/0f5371f8879607eb95b8e63badca227e
