### ISSUE TITLE
Texture deswizzling for Needy Streamer Overdose Nintendo Switch version

### ISSUE THREAD

**Issue by DSwizzy** [Vadim07/AssetStudio#33]
This game doesn't deswizzle textures at the moment, if possible could this be looked into soon? Thank You

P.S. at the very least Idol Mahjong Final Romance 4 Remaster was able to deswizzle the textures and everything completely well so thanks for that too!

**Comment by aelurum** [comment]
Attach some sample files

**Comment by DSwizzy** [comment]
![@apricot_skgt](https://github.com/aelurum/AssetStudio/assets/91478676/8ee12d02-db51-4c71-be24-55b8b7afa6aa)
![AreaTex](https://github.com/aelurum/AssetStudio/assets/91478676/58d70c4d-5ab0-4c5e-9926-ed292d4d9998)
![angle5_blood](https://github.com/aelurum/AssetStudio/assets/91478676/1acb6aec-feb0-48d1-ab46-09713fedac16)
![balloon](https://github.com/aelurum/AssetStudio/assets/91478676/94f47795-a714-487d-938b-5bddfe69e8ff)
![body_bg](https://github.com/aelurum/AssetStudio/assets/91478676/113c18d6-55a5-4880-be4c-fa4062e1c8ae)
![body_cho_l_001](https://github.com/aelurum/AssetStudio/assets/91478676/32593df0-f859-4c1f-ae9e-006c9a36e590)
![body_light_002](https://github.com/aelurum/AssetStudio/assets/91478676/5a099c26-fb3e-4d65-8f33-eab38cc335b7)
![Font Texture](https://github.com/aelurum/AssetStudio/assets/91478676/7574d7e0-37ef-48e2-8c0e-9cfadf515f15)
![kyouizon_bg_003_dot](https://github.com/aelurum/AssetStudio/assets/91478676/2ceca997-5085-4d99-b13c-b9bd4ecb99a3)
![result_bg_tile](https://github.com/aelurum/AssetStudio/assets/91478676/f3c6e1a6-c172-4af7-8811-42fd9356311e)
![Square](https://github.com/aelurum/AssetStudio/assets/91478676/be0178a0-b978-4773-b565-f0668f052496)
![Shutter_007](https://github.com/aelurum/AssetStudio/assets/91478676/d192d0f4-2dcd-4fd3-be84-b5ee9ccc351a)
![water_1](https://github.com/aelurum/AssetStudio/assets/91478676/544b4f88-2df5-4912-bb90-41ba5c99c8bf)
![water_4](https://github.com/aelurum/AssetStudio/assets/91478676/762e7ef5-5cb3-457c-bccf-427c90a8aab2)
![water_5](https://github.com/aelurum/AssetStudio/assets/91478676/814dc67c-4a38-4eab-8573-ca60c5f31884)

**Comment by DSwizzy** [comment]
these are just the only examples i've found so far, there's a few more

**Comment by aelurum** [comment]
I see
but I need an asset bundle file itself with these textures

**Comment by DSwizzy** [comment]
> I see but I need an asset bundle file itself with these textures

hmm... it seems to show up just fine now i apologize for wasting your time, so i'm assuming the romfs files that i dumped awhile ago was incorrectly dumped and i guess some were corrupted in the process but now actually shows up finally

Thank you for the awesome update once again! 👍 and you can close this if you like

**Comment by aelurum** [comment]
In fact, it looks like you tried to load bundles from the base version with resources from the updated version of the game.
Or vice versa.
But it's still weird, overwriting the resource file, which can happen in the original Studio, shouldn't happen in this version. 🤔
