### ISSUE TITLE
Mesh files exported incorrectly [CLI]

### ISSUE THREAD

**Issue by GHSASH** [Vadim07/AssetStudio#38]
The mesh files are being exported with commas instead of periods for the vertices when converted to the OBJ format, which ends up corrupting the file. I conducted a test comparing the files generated by the GUI and the CLI, and it seems that this issue affects only the CLI version. Simply replacing the commas with periods makes the OBJ file work correctly

![image](https://github.com/aelurum/AssetStudio/assets/34551276/0fe499da-e2ef-4d74-a059-9064b4759056)

**Comment by aelurum** [comment]
Oh, regional format bugs, my beloved)
