### ISSUE TITLE
Unable to load object

### ISSUE THREAD

**Issue by moonskae** [Vadim07/AssetStudio#46]
Hi. Ive been trying to see the files from the mobile game Shining Nikki and I used to be able to do it before. The game had a recent update and now I cant seem to open the mesh files. Textures load fine, but meshes seem to have some issues. 

I get the following message when trying to load the files in AssetStudio:

> Unable to load object
> [Warning] Assets CAB-118a61376bf239bc6ad21673ca396376
> [Warning] Path D:\RIP\Shining Nikki\Ripping tools\Test\s0554_2d.cut
> [Warning] Type Material
> [Warning] PathID 7030046753368706209
> [Warning] System.IO.EndOfStreamException: Unable to read beyond the end of the stream.
> [Warning]    at System.IO.BinaryReader.InternalRead(Int32 numBytes)
> [Warning]    at System.IO.BinaryReader.ReadSingle()
> [Warning]    at AssetStudio.EndianBinaryReader.ReadSingle() in L:\GIT\AssetStudioMod\AssetStudio\EndianBinaryReader.cs:line 91
> [Warning]    at AssetStudio.BinaryReaderExtensions.ReadColor4(BinaryReader reader) in L:\GIT\AssetStudioMod\AssetStudio\Extensions\BinaryReaderExtensions.cs:line 98
> [Warning]    at AssetStudio.UnityPropertySheet..ctor(ObjectReader reader) in L:\GIT\AssetStudioMod\AssetStudio\Classes\Material.cs:line 58
> [Warning]    at AssetStudio.Material..ctor(ObjectReader reader) in L:\GIT\AssetStudioMod\AssetStudio\Classes\Material.cs:line 119
> [Warning]    at AssetStudio.AssetsManager.ReadAssets() in L:\GIT\AssetStudioMod\AssetStudio\AssetsManager.cs:line 564

You can find the assets I've been trying to open here:
[Shining nikki assets.zip](https://github.com/user-attachments/files/16494926/Shining.nikki.assets.zip)

They are .cut because I need to use vgmtoolbox to remove the first 8 bytes in order to open them on ASsetStudio. If you need the original assets, I can also provide them.

Thank you!

**Comment by aelurum** [comment]
Use this one: https://github.com/Modder4869/StudioDev/actions/runs/10304826599
there is also a tutorial: https://gist.github.com/Modder4869/0f5371f8879607eb95b8e63badca227e (not for the game, but how to work with that Studio)
