### ISSUE TITLE
undicing of sprites?

### ISSUE THREAD

**Issue by suteakanon** [Vadim07/AssetStudio#51]
Just wondering if it would be possible to add a function to undo sprite dicing. For something like this:
![20241012](https://github.com/user-attachments/assets/4605557c-1db0-4d33-ab9f-ca425d843af8)

Here's the bundle of the above pic.
[bundle.zip](https://github.com/user-attachments/files/17348332/bundle.zip)

**Comment by aelurum** [comment]
Yeah, it's possible (thanks to K0lb3).
You can find a version of AssetStudio that supports such sprites on the [UnityPy](https://github.com/K0lb3/UnityPy/) Discord server (https://discord.com/channels/603359898507673630/1293664578827194419/1293698198334083092).
But the code in that version is mostly for testing and works quite slowly.

UnityPy already supports such sprites, but there is some bug with them in the current version (1.20.4).

I plan to add support for such sprites which are based on Elringus' lib, as well as some other variation that contains only diced textures without sprites. Not sure when, though.

**Comment by suteakanon** [comment]
Wow, thanks so much! The alternate version seems to work perfectly for my current needs.
