### ISSUE TITLE
Can't preview AudioClip from old Unity versions (WebPlayer, 2.x-4.x)

### ISSUE THREAD

**Issue by AloXado320** [Vadim07/AssetStudio#53]
It used to be possible on the original version of AssetStudio (as seen on the left, right is the latest mod version)

For reference, the game I loaded is "Phineas and Ferb - Dimension of Doom" using "Load file" (as .unity3d)
The same issue happens with "Phineas and Ferb - Transport-inators of Doom"

![image](https://github.com/user-attachments/assets/771d61b4-48fe-4964-9b39-d3f38230a5fe)

**Comment by AloXado320** [comment]
Update: It seems that old Unity versions are affected, not just Web Player games
Here's "Garfield Kart" having the same issue:

![image](https://github.com/user-attachments/assets/14610939-6214-4187-98a8-75a5b2a0a48d)

**Comment by aelurum** [comment]
Yeah, thanks for reporting this.
It's already fixed, I'll push a commit later.
