### ISSUE TITLE
Totally Spies - Cyber Mission Unable to Load

### ISSUE THREAD

**Issue by tippy123** [Vadim07/AssetStudio#54]
HI

Trying to load these files into Asset Studio did not work.

https://www.dropbox.com/scl/fi/mfqowvkwkcb835s5wwjyc/Totally-Spies-Cyber-Mission-file.rar?rlkey=0k3xfyitg0c2gwcqx4u8vkyyp&st=qqb2xieh&dl=0 

https://www.dropbox.com/scl/fi/km17avya1oesbh0dvywp6/bbb.PNG?rlkey=6kfa9j347wjt5lpvsriqcfg4l&st=n5nqa8zk&dl=0

Here is a Drop Box link some game file and photo of the error too 
Thanks

**Comment by aelurum** [comment]
Hello.
The current build of AssetStudioMod can already load assets from Unity 6.
You can download the latest build by clicking "Download latest build" button in the Readme or [here](https://ci.appveyor.com/project/aelurum/assetstudiomod/branch/AssetStudioMod/artifacts).
