### ISSUE TITLE
Is support for higher unity versions coming?

### ISSUE THREAD

**Issue by enarkay** [Vadim07/AssetStudio#6]
A few days ago I ran into a problem where AssetStudio could not properly parse MB files of a game which was made with Unity version 2022.2.12

The game is called "I am Dave", and it's free to download and play so just in case you want to take a look, below is the link to the game.
https://dnsatan.itch.io/i-am-dave

With that said, I was wondering if support for higher unity versions, such as 2022.2, are coming/planned/being considered in the future.
Or will the support versions permanently be fixed to 3.4 - 2022.1, as is at the moment?

**Comment by aelurum** [comment]
Hi
Sadly, most likely the last one
I can't continue Perfare's work and keep AssetStudio up to date or fix some internal bugs
I just lack of knowledge to do that
This fork is mainly focused on UI modifications and functionality enhancements
Of course, there's a small chance that someone will make a PR that adds support for new Unity versions.. or maybe I'll find a solution somewhere on github one day..
But yeah, you shouldn't expect support for higher unity versions from this fork

There are other programs that can work with new Unity versions, such as [AssetRipper](https://github.com/AssetRipper/AssetRipper), [UABEA](https://github.com/nesrak1/UABEA),..
You can try them

**Comment by enarkay** [comment]
Fully understandable- but I thank you very much anyways for updating AssetStudio and maintaining it even to this point. I've been able to load a lot of games without errors in your fork of AssetStudio, unlike how they popped up 50 error windows in the original AS and it was such a tedious labor just to try and load one game by closing those error windows everytime they pop up.

As for other programs, I am already using UABEA very well. It's just that AssetStudio is kind of the beginnig point of my workflow. I usually try to understand the general approach I should be taking by looking in AS, then work with UABEA for working with specific assets/files :)

**Comment by aelurum** [comment]
@enarkay
