### ISSUE TITLE
Reverse "Go to scene hierarchy"?

### ISSUE THREAD

**Issue by Timon1221** [Vadim07/AssetStudio#7]
Could you add such a feature?
https://github.com/Perfare/AssetStudio/issues/1031

**Comment by aelurum** [comment]
Hi
Well, it's possible, but it depends on what exactly you want.

If you want to see related assets only for a selected node, then you can test this build: [AssetStudioMod v0.17.1.4](https://ci.appveyor.com/project/aelurum/assetstudiomod/build/artifacts)

But if you want to see related assets for a selected node and all of its child nodes.. then it will require some different and more complex implementation. And I don't plan to do something like that right now.

**Comment by Timon1221** [comment]
> If you want to see related assets only for a selected node, then you can test this build: [AssetStudioMod v0.17.1.4](https://ci.appveyor.com/project/aelurum/assetstudiomod/build/artifacts)

That's what I've been looking for. Thank you.
